package com.restaurantdeliverysystem.dao;

import com.restaurantdeliverysystem.model.Vendor;
import com.restaurantdeliverysystem.util.DBConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object for Vendor entity. Provides methods to perform CRUD
 * operations on the vendors table in the database.
 */
public class VendorDAO {

    /* Retrieves all vendors from the database, ordered by name. */
    public List<Vendor> getAllVendors() throws SQLException {
        List<Vendor> list = new ArrayList<>();
        String sql = "SELECT * FROM vendors ORDER BY name";
        try (Statement st = DBConnection.getConnection().createStatement();
                ResultSet rs = st.executeQuery(sql)) {
            while (rs.next())
                list.add(map(rs));
        }
        return list;
    }

    /* Retrieves a single vendor by its ID. Returns null if not found. */
    public Vendor getById(int id) throws SQLException {
        String sql = "SELECT * FROM vendors WHERE vendor_id = ?";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next())
                    return map(rs);
            }
        }
        return null;
    }

    /*
     * Inserts a new vendor into the database. The vendor_id is auto-generated by
     * the database.
     */
    public void insert(Vendor v) throws SQLException {
        String sql = "INSERT INTO vendors (name, address, phone_number) VALUES (?,?,?)";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setString(1, v.getName());
            ps.setString(2, v.getAddress());
            ps.setString(3, v.getPhoneNumber());
            ps.executeUpdate();
        }
    }

    /*
     * Updates an existing vendor in the database. The vendor_id must already exist.
     */
    public void update(Vendor v) throws SQLException {
        String sql = "UPDATE vendors SET name=?, address=?, phone_number=?, WHERE vendor_id=?";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setString(1, v.getName());
            ps.setString(2, v.getAddress());
            ps.setString(3, v.getPhoneNumber());
            ps.setInt(5, v.getVendorId());
            ps.executeUpdate();
        }
    }

    public void delete(int id) throws SQLException {
        String sql = "DELETE FROM vendors WHERE vendor_id = ?";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setInt(1, id);
            ps.executeUpdate();
        }
    }

    private Vendor map(ResultSet rs) throws SQLException {
        return new Vendor(
                rs.getInt("vendor_id"),
                rs.getString("name"),
                rs.getString("address"),
                rs.getString("phone_number"));
    }
}
