package com.restaurantdeliverysystem.dao;

import com.restaurantdeliverysystem.model.Customer;
import com.restaurantdeliverysystem.util.DBConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/** Data Access Object for Customer entity. Provides methods to perform CRUD operations on the customers table in the database. */
public class CustomerDAO {

    /** Retrieves all customers from the database, ordered by last name and first name. */
    public List<Customer> getAllCustomers() throws SQLException {
        List<Customer> list = new ArrayList<>();
        String sql = "SELECT * FROM customers ORDER BY last_name, first_name";
        try (Statement st = DBConnection.getConnection().createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) list.add(map(rs));
        }
        return list;
    }

    /** Retrieves a single customer by its ID. Returns null if not found. */
    public Customer getById(int id) throws SQLException {
        String sql = "SELECT * FROM customers WHERE customer_id = ?";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return map(rs);
            }
        }
        return null;
    }

    /** Inserts a new customer into the database. The customer_id is auto-generated by the database. */
    public void insert(Customer c) throws SQLException {
        String sql = "INSERT INTO customers (first_name, last_name, address, phone_number, payment_method) VALUES (?,?,?,?,?)";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setString(1, c.getFirstName());
            ps.setString(2, c.getLastName());
            ps.setString(3, c.getAddress());
            ps.setString(4, c.getPhoneNumber());
            ps.setString(5, c.getPaymentMethod());
            ps.executeUpdate();
        }
    }

    /** Updates an existing customer in the database. The customer_id must already exist. */
    public void update(Customer c) throws SQLException {
        String sql = "UPDATE customers SET first_name=?, last_name=?, address=?, phone_number=?, payment_method=? WHERE customer_id=?";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setString(1, c.getFirstName());
            ps.setString(2, c.getLastName());
            ps.setString(3, c.getAddress());
            ps.setString(4, c.getPhoneNumber());
            ps.setString(5, c.getPaymentMethod());
            ps.setInt(6, c.getCustomerId());
            ps.executeUpdate();
        }
    }

    /** Deletes a customer from the database by its ID. */
    public void delete(int id) throws SQLException {
        String sql = "DELETE FROM customers WHERE customer_id = ?";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setInt(1, id);
            ps.executeUpdate();
        }
    }

    /** Maps a ResultSet row queried from the db to a Customer object. */
    private Customer map(ResultSet rs) throws SQLException {
        return new Customer(
            rs.getInt("customer_id"),
            rs.getString("first_name"),
            rs.getString("last_name"),
            rs.getString("address"),
            rs.getString("phone_number"),
            rs.getString("payment_method")
        );
    }
}
