package com.restaurantdeliverysystem.dao;

import com.restaurantdeliverysystem.model.Driver;
import com.restaurantdeliverysystem.util.DBConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/** Data Access Object for Driver entity. Provides methods to perform CRUD operations on the drivers table in the database. */
public class DriverDAO {

    public List<Driver> getAllDrivers() throws SQLException {
        List<Driver> list = new ArrayList<>();
        String sql = "SELECT * FROM drivers ORDER BY last_name, first_name";
        try (Statement st = DBConnection.getConnection().createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) list.add(map(rs));
        }
        return list;
    }

    /** Retrieves all available drivers (status = 'available') from the database, ordered by last name. */
    public List<Driver> getAvailableDrivers() throws SQLException {
        List<Driver> list = new ArrayList<>();
        String sql = "SELECT * FROM drivers WHERE status = 'available' ORDER BY last_name";
        try (Statement st = DBConnection.getConnection().createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) list.add(map(rs));
        }
        return list;
    }

    /** Inserts a new driver into the database. Id is autgenerated by the database. */
    public void insert(Driver d) throws SQLException {
        String sql = "INSERT INTO drivers (first_name, last_name, phone_number, status) VALUES (?,?,?,?)";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setString(1, d.getFirstName());
            ps.setString(2, d.getLastName());
            ps.setString(3, d.getPhoneNumber());
            ps.setString(4, d.getStatus());
            ps.executeUpdate();
        }
    }

    /** Updates an existing driver in the database. The driver_id must already exist. */
    public void update(Driver d) throws SQLException {
        String sql = "UPDATE drivers SET first_name=?, last_name=?, phone_number=?, status=? WHERE driver_id=?";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setString(1, d.getFirstName());
            ps.setString(2, d.getLastName());
            ps.setString(3, d.getPhoneNumber());
            ps.setString(4, d.getStatus());
            ps.setInt(5, d.getDriverId());
            ps.executeUpdate();
        }
    }

    /** Updates the status of a driver (e.g., "available", "on delivery", "off duty").
     * @param driverId The ID of the driver to update.
     * @param status The new status to set for the driver.
    */
    public void updateStatus(int driverId, String status) throws SQLException {
        String sql = "UPDATE drivers SET status=? WHERE driver_id=?";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setString(1, status);
            ps.setInt(2, driverId);
            ps.executeUpdate();
        }
    }

    /** Deletes a driver from the database by its ID. */
    public void delete(int id) throws SQLException {
        String sql = "DELETE FROM drivers WHERE driver_id = ?";
        try (PreparedStatement ps = DBConnection.getConnection().prepareStatement(sql)) {
            ps.setInt(1, id);
            ps.executeUpdate();
        }
    }

    /** Maps a ResultSet row queried from the db to a Driver object. */
    private Driver map(ResultSet rs) throws SQLException {
        return new Driver(
            rs.getInt("driver_id"),
            rs.getString("first_name"),
            rs.getString("last_name"),
            rs.getString("phone_number"),
            rs.getString("status")
        );
    }
}
